name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Changes will deploy only when you push to the main branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-south1
  # Update these two lines to match your actual names:
  SERVICE_NAME: nestjs-service
  ARTIFACT_REPO:  nestjs-repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Authorize Docker
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Container
        run: |
          # The tag uses the GitHub commit SHA to make every version unique
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          
          docker build -t $DOCKER_TAG .
          docker push $DOCKER_TAG
          
          # Pass the tag to the next step
          echo "IMAGE_TAG=$DOCKER_TAG" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_TAG }}
          # Optional: Allows public access. Remove if your API is private.
          flags: '--allow-unauthenticated'